# Generated by Django 5.2.7 on 2025-10-25 08:58

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Неизвестная комета', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observation_time', models.DateTimeField(help_text='Время наблюдения (UTC)')),
                ('ra_hms', models.CharField(help_text='Прямое восхождение (чч:мм:сс.сс)', max_length=15)),
                ('dec_dms', models.CharField(help_text='Склонение (+/-дд:мм:сс.с)', max_length=15)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='comet_photos/')),
                ('comet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='orbit_calculator.comet')),
            ],
        ),
        migrations.CreateModel(
            name='OrbitalElements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semimajor_axis', models.FloatField(help_text='Большая полуось (а.е.)')),
                ('eccentricity', models.FloatField(help_text='Эксцентриситет (e)', validators=[django.core.validators.MinValueValidator(0.0)])),
                ('inclination', models.FloatField(help_text='Наклонение (град)')),
                ('ra_of_node', models.FloatField(help_text='Долгота восходящего узла (град)')),
                ('arg_of_pericenter', models.FloatField(help_text='Аргумент перицентра (град)')),
                ('time_of_pericenter', models.DateTimeField(help_text='Время прохождения перигелия (T0)')),
                ('calculation_date', models.DateTimeField(auto_now=True)),
                ('rms_error', models.FloatField(blank=True, help_text='Среднеквадратичная ошибка подгонки', null=True)),
                ('comet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='orbit_calculator.comet')),
            ],
        ),
        migrations.CreateModel(
            name='CloseApproach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approach_date', models.DateTimeField(help_text='Дата минимального сближения')),
                ('min_distance_au', models.FloatField(help_text='Минимальное расстояние (а.е.)')),
                ('orbital_elements', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approaches', to='orbit_calculator.orbitalelements')),
            ],
        ),
    ]
