# Generated by Django 5.2.7 on 2025-10-25 09:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orbit_calculator', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='observation',
            name='dec_dms',
        ),
        migrations.RemoveField(
            model_name='observation',
            name='ra_hms',
        ),
        migrations.AddField(
            model_name='observation',
            name='dec_deg',
            field=models.FloatField(default=0, help_text='Склонение (Dec) в градусах', validators=[django.core.validators.MinValueValidator(-90.0), django.core.validators.MaxValueValidator(90.0)]),
        ),
        migrations.AddField(
            model_name='observation',
            name='ra_deg',
            field=models.FloatField(default=0, help_text='Прямое восхождение (RA) в градусах', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(360.0)]),
        ),
    ]
