# Generated by Django 5.2.7 on 2025-10-25 13:44

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orbit_calculator', '0002_remove_observation_dec_dms_remove_observation_ra_hms_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='closeapproach',
            name='orbital_elements',
        ),
        migrations.AddField(
            model_name='closeapproach',
            name='elements',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='approach_prediction', to='orbit_calculator.orbitalelements'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='closeapproach',
            name='approach_date',
            field=models.DateTimeField(help_text='Дата и время минимального сближения'),
        ),
        migrations.AlterField(
            model_name='closeapproach',
            name='min_distance_au',
            field=models.FloatField(help_text='Минимальное расстояние до Земли в а.е.'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='dec_deg',
            field=models.FloatField(help_text='Склонение (Dec) в градусах', validators=[django.core.validators.MinValueValidator(-90.0), django.core.validators.MaxValueValidator(90.0)]),
        ),
        migrations.AlterField(
            model_name='observation',
            name='ra_deg',
            field=models.FloatField(help_text='Прямое восхождение (RA) в градусах', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(360.0)]),
        ),
    ]
